version: '2'
services:
  rstudioserver:
    restart: always
    image: rocker/verse
    volumes:
      - /home/playground:/home/playground
    ports:
      - 8787:8787
    environment:
      USER: 'user'
      PASSWORD: 'pass'
    links:
      - redis
  redis:
    restart: always
    image: redis 
